package mybiblioteca;

public class menuPrincipal extends javax.swing.JFrame {

    public menuPrincipal() {
        initComponents();
        crearVentana();
    }
    
     private void crearVentana() {
        setTitle("Menú principal | myBiblioteca v2020");
        //setSize(480, 400);
        //setLocationRelativeTo(null);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setResizable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonSalirMenu = new javax.swing.JButton();
        botonPersonas = new javax.swing.JButton();
        botonCompras = new javax.swing.JButton();
        botonVentas = new javax.swing.JButton();
        botonArriendos = new javax.swing.JButton();
        botonLibros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("myBiblioteca v2020");
        setAlwaysOnTop(true);
        setLocation(new java.awt.Point(50, 5));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Menu principal - myBibilioteca v2020");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        botonSalirMenu.setText("Salir");
        botonSalirMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirMenuActionPerformed(evt);
            }
        });

        botonPersonas.setText("Módulo de Personas");
        botonPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonasActionPerformed(evt);
            }
        });

        botonCompras.setText("Módulo de Compras");
        botonCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprasActionPerformed(evt);
            }
        });

        botonVentas.setText("Módulo de Ventas");
        botonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVentasActionPerformed(evt);
            }
        });

        botonArriendos.setText("Módulo de Arriendos");
        botonArriendos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArriendosActionPerformed(evt);
            }
        });

        botonLibros.setText("Módulo de Libros");
        botonLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLibrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonPersonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonVentas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonArriendos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(botonLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(botonSalirMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(botonPersonas)
                .addGap(18, 18, 18)
                .addComponent(botonCompras)
                .addGap(18, 18, 18)
                .addComponent(botonVentas)
                .addGap(18, 18, 18)
                .addComponent(botonArriendos)
                .addGap(18, 18, 18)
                .addComponent(botonLibros)
                .addGap(18, 18, 18)
                .addComponent(botonSalirMenu)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirMenuActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirMenuActionPerformed

    private void botonPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonasActionPerformed
        // TODO add your handling code here:
        new frmPersonas().setVisible(true);
    }//GEN-LAST:event_botonPersonasActionPerformed

    private void botonComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprasActionPerformed
        // TODO add your handling code here:
        new frmCompras().setVisible(true);
    }//GEN-LAST:event_botonComprasActionPerformed

    private void botonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVentasActionPerformed
        // TODO add your handling code here:
        new frmVentas().setVisible(true);
    }//GEN-LAST:event_botonVentasActionPerformed

    private void botonArriendosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArriendosActionPerformed
        // TODO add your handling code here:
        new frmArriendos().setVisible(true);
    }//GEN-LAST:event_botonArriendosActionPerformed

    private void botonLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLibrosActionPerformed
        // TODO add your handling code here:
        new frmLibros().setVisible(true);
    }//GEN-LAST:event_botonLibrosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new menuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonArriendos;
    private javax.swing.JButton botonCompras;
    private javax.swing.JButton botonLibros;
    private javax.swing.JButton botonPersonas;
    private javax.swing.JButton botonSalirMenu;
    private javax.swing.JButton botonVentas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables


}
